# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target ‘MyBarMusic' do

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

# Pods for MyBarMusic

    pod 'SlideMenuControllerSwift'

    pod 'HandyJSON', '~> 1.7.2'

end
